### ISSUE TITLE
ImportError: cannot import name 'agi' from 'aiflow'

### ISSUE THREAD

**Issue by gradTV** [yukiarimo/yuna-ai#134]
**Describe the bug**

**To Reproduce**
1. Go to 'download bibliotec airflow'
2. Click on 'cmd'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![Image](https://github.com/user-attachments/assets/549d6577-1098-464e-acb5-111cdcea4b08)

**Comment by yukiarimo** [comment]
Have you installed AiFlow?

**Comment by gradTV** [comment]
![Image](https://github.com/user-attachments/assets/a07d91ad-d436-48e7-adf6-5c91e711c1f9)

**Comment by yukiarimo** [comment]
1. Will update it today
2. Please don’t forget to reinstall when it updates (cause some stuff may be deprecated on older one)

**Comment by ChangAlvin** [comment]
> 1. Will update it today
> 2. Please don’t forget to reinstall when it updates (cause some stuff may be deprecated on older one)

Hello yukia, any good news? I encountered the same problem。seems no agi in aiflow1.0.0, which version you use?

**Comment by yukiarimo** [comment]
Version 2.0.0. Gonna release 2.1.0 today in a few hours!

**Comment by yukiarimo** [comment]
Please update AiFlow and Yuna Server

**Comment by gradTV** [comment]
![Image](https://github.com/user-attachments/assets/ac300980-123d-4fc3-b585-e718741c3fce) ... 

Then I download airflow and this error again.

PS C:\Users\asasi\OneDrive\Desktop\yuna-ai-7.2> python index.py
Traceback (most recent call last):
  File "C:\Users\asasi\OneDrive\Desktop\yuna-ai-7.2\index.py", line 10, in <module>
    from aiflow import agi, history
ImportError: cannot import name 'agi' from 'aiflow' (C:\Users\asasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiflow\__init__.py)

**Git bash:**
![Image](https://github.com/user-attachments/assets/a3040231-3e33-4c4f-b1ff-fc2cc2998eda) 
![Image](https://github.com/user-attachments/assets/f3e532a6-fe46-4b77-8878-c3e274b33208)

What's wrong?

**Comment by gradTV** [comment]
I'm talking about the fact that I deleted all the old libraries

**Comment by ChangAlvin** [comment]
> Version 2.0.0. Gonna release 2.1.0 today in a few hours!

after upgrade aiflow to 2.0.0 , Encountering another problem
ImportError: cannot import name 'get_text_embedding' from partially initialized module 'aiflow.utils'

**Comment by ChangAlvin** [comment]
> Please update AiFlow and Yuna Server

after update and recompiled, another problem occured.

Traceback (most recent call last):
  File "/home/robinai3/yuna-ai/index.py", line 10, in <module>
    from aiflow import agi, history
  File "/root/miniconda3/envs/yunaai/lib/python3.10/site-packages/aiflow/agi.py", line 6, in <module>
    from aiflow.utils import get_config, clearText, search_web, get_html, get_transcript, load_kokoro_model, get_text_embedding, load_config
  File "/root/miniconda3/envs/yunaai/lib/python3.10/site-packages/aiflow/utils.py", line 21, in <module>
    from aiflow.models.kokoro import model as kokoro
  File "/root/miniconda3/envs/yunaai/lib/python3.10/site-packages/aiflow/models/kokoro/model.py", line 6, in <module>
    from aiflow.utils import get_text_embedding
ImportError: cannot import name 'get_text_embedding' from partially initialized module 'aiflow.utils' (most likely due to a circular import) (/root/miniconda3/envs/yunaai/lib/python3.10/site-packages/aiflow/utils.py)
